### ISSUE TITLE
Замечания по проекту

### ISSUE THREAD

**Issue by Andrey540** [AlexeyDudin/todos_test_project#1]
- [x] Сервис `class TodoService extends AbstractController` сейчас по сути является не сервисом, а контроллером. Он зависит от AbstractController, работает с запросами $request, и формирует json. Сервис не должен работать с запросами напрямую. Контроллер (TodoController) должен извлекать из запросов нужную информацию и передавать её в сервис (TodoService). Сервис должен осуществлять действие и возвращать результат, лучше в виде DTO, чтобы из контрллера нельзя было изменить модель. Модель должна меняться только в сервисе и не должна из него выходиьт наружу. Контроллер по DTO уже должен формировать ответ клиенту.
- [x] Сейчас все исключения преобразуются в код ответа 404 `catch(\Exception $e) { return $this->json($e->getMessage(), 404); }`, что является неверным, тк могут быть неверные параметры запроса, в этом случае должен возвращаться код 400, а в случае, если возникла ошибка при обращении к базе 500.
- [x] `$todoRepository->createQueryBuilder('t')->where('t.executed = TRUE')` сейчас сервис фактически сам формирует запросы, а не репозиторий. Формирование запросов должно быть скрыто в репозиторие.
- [x] В репозиторие параметр `, bool $flush = false` всегда парадаётся true, нужен ли он вообще?

**Comment by AlexeyDudin** [comment]
- Касаемо `$todoRepositoty->createQueryBuilder('t')->where('t.executed = TRUE')`: По моей логике это должно быть так: Репозиторий отвечает непосредственно за работу с базой данных. Сервис непосредственно являет собой логику работы приложения. Контроллер занимается обработкой входящих запросов. Раз сервис определяет логику работы приложения, то он и должен сгенерировать запрос того, что ему нужно. А репозиторий уже должен выполнить этот запрос.
- В дополнение к своему аргументу. Писал аналогичные задачи на C#. В нем есть такая вещь, как LINQ. Именно благодаря LINQ логика работы программы полностью описывается в Service. А уже EntityFramework сам преобразует LINQ-запрос в SQL-запрос. Пример не совсем хороший, но: https://github.com/AlexeyDudin/BookOfRecipes/blob/master/Application/Users/UserService.cs

**Comment by AlexeyDudin** [comment]
Касаемо параметра `, bool $flush = false` - конкретно в данном приложении это действительно не нужно. Но для масштабируемых приложений это необходимо. Например, когда нам надо подготовить данные, но нам не нужно их сохранять "вот прямо сейчас" в базу данных. Поэтому этот функционал я оставил "as is".
Все остальные изменения я внес в код и залил новым коммитом

**Comment by Andrey540** [comment]
Сервисный слой не должен завязываться на инфраструктуру, когда запрос формирует сам сервис, получается, что он знает о том как устроен репозиторий. Сервис должен зависеть от интерфейса репозитория, чтобы в любой момент времени репозиторий можно было заменить, например, на репозиторий работающий не с БД, а с файлами или хранящим объекты в памяти. Также такой подход позволяет протестировать сервис (использование в качестве абстракций интерфейсов и внедрение зависимостей).
И не важно на каком языке написан код.
